name: pre-commit

on:
  workflow_call:
  pull_request_target:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Adjusted to Python 3.9
          cache: "pip"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: pre-commit/action@v3.0.1

      - name: Post PR comment on failure
        if: failure() && github.event_name == 'pull_request_target'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :x: **pre-commit** failed.
            Please run `pre-commit run --all-files` locally and commit the changes.
            Find more information in the repository's CONTRIBUTING.md
